[package]
name = "plugin-tools-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_derive.workspace = true
serde_yaml.workspace = true

tools = { path = "../tools" }

[lints]
workspace = true
