[package]
name = "plugin-phrases"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_yaml.workspace = true
matrix-sdk.workspace = true
rand = "0.8"

plugin-core = { path = "../plugin-core" }

[lints]
workspace = true
